# base image
FROM ubuntu:latest

# OPERATIONS & # Install libraries
RUN <> &&

# COPY the code
COPY  ./ /usr/app

# Expose the ports for networking

EXPOSE 8080

# ENTRYPOINT or CMD to start the application    

CMD [ "python3","/usr/app/test.py"]

