# example 4 -ARGUMENTS

## variables which can be overwritten during image build
# docker build time 
ARG IMAGE_VERSION=latest

FROM ubuntu:${IMAGE_VERSION}
# command - overwritten
# can only be run into -it mode

CMD ["/bin/bash"]


